name: logger_flutter
description: Flutter extension for logger. Please go there for documentation.
version: 1.0.2
homepage: https://inspireui.com

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger: 2.0.1
  sensors: 2.0.3
  google_fonts: ^5.1.0
  event_bus: 2.0.0
